## A basic GitHub Actions workflow for your Quarkus application.

name: Codeowners

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Codeowners
        uses: madytw/codeowners-action@main
        with:
          github-token: ${{ secrets.PACKAGE_TOKEN }}
          my-input: 'some input'
